### ISSUE TITLE
Bounty: Fix BOINC Windows Packaging

### ISSUE THREAD

**Issue by makeasnek** [TheSCInitiative/bounties#12]
Context: See relevant issue in BOINC repo https://github.com/BOINC/boinc/issues/5065

**https://github.com/parvit is currently working on this bounty. This bounty will be re-opened for other applicants if need be**

**Requirements to claim bounty:**
- Submit code to BOINC repo and have it approved by maintainers, following all coding standards used by the repo and making any style and other edits requested by them. Note that 

**Contribute to this Bounty**
You can contribute to this bounty by donating [to SCI](https://thesciencecommons.org/donate/) directly, get a nice tax deduction, and we will spend those donated funds on our bounty programs. The higher the bounty, the more likely a developer will come along to claim it!

**Bounty amount: $500**

You will also get the satisfaction of knowing you are helping a software and ecosystem which supports the progress of science. 

**Claiming bounty**

Comment below if you want to indicate you are working on the bounty (though this is not required) or if you have any questions. BountySource bounty will paid under the BountySource terms (if bounty payers vote that your change fixes the issue). 

**About SCI**
The SCI is a US 501(c)(3) non-profit organization dedicated to rebuilding the bridge of participation and trust between the public and the scientific process. We support tools and infrastructure that enable people to learn about and engage with science. Follow our work via our [free newsletter on substack](https://thesciencecommons.substack.com/).

**Comment by parvit** [comment]
PR created: https://github.com/BOINC/boinc/pull/5355

**Comment by makeasnek** [comment]
Thanks Parvit! We'll wait from feedback and merge from the BOINC team

**Comment by makeasnek** [comment]
Bounty is complete, payment sent today

**Comment by parvit** [comment]
Hi, i can confirm the payment, i remain available for support if necessary.
