### ISSUE TITLE
Bounty DRAFT Quickmag replacement

### ISSUE THREAD

**Issue by makeasnek** [TheSCInitiative/bounties#14]
**Context:**
- Gridcoin is a cryptocurrency which rewards users for contributing their computational power to scientific research
- In order to determine whether or not the rewards would be worth it for any given user, the user must know the quantity of the reward
- A rough estimate of reward quantity can be obtained by scraping stats from BOINC project websites (who conveniently report it in a .csv file), doing some math, and knowing the user's hardware
- A website used to offer this (Quickmag) but it has been offline for some time and the creator has abandoned it

**Requirements to claim bounty:**

- Build a replacement for the Quickmag website.

Website Functionality:
- The website shall present a user with a query box in which they can type the name of their hardware. Examples of hardware names would be 'i7-9700k' 'AMD RAEDON 590x' etc. An automatic dropdown selection menu shall provide suggestions based on known hardware names. Upon selection, it shall provide the user with a table. Each row is a BOINC project, with columns for the Gridcoin earned by top 4 hosts on that project using that hardware and the average for a host using that hardware.
- The hardware names shall be scraped from the websites of various BOINC projects. This scraping should occur once every 7 days with retries once every 24 hours for any sites which didn't get updated properly. You may store this information in an sql database, a text file, or any other format of your choosing. The BOINC projects provide this data in a .csv.gz fie for easy ingestion.
- Note that some hardware types may be listed multiple times or in multiple ways. For example 'i7-9700k rev1' 'i7-9700k rev2'. If a user searched for just 'i7-9700k' it should return data based on ALL hardware which matches including all known revs. However if a user searches for 'i7-9700k rev1' it should return rev1 only, not rev1 + rev 2. 
- Once the hardware is identified, the software shall find Top 4 users with the highest credit using that hardware (provided in the .gz file) and the average credit using that hardware.
- Once the credit amount is identified, the credit will need to be converted into expected Gridcoin rewards. This can be fetched and calculated from a connected Gridcoin wallet or from a JSON url which will be provided for you. The credit -> GRC ratio for each project shall be cached so as to not make a request for it > once every 5 days. Code to fetch this from wallets in python already exists and you may use it/it will be provided to you.
- The website shall be able to run and service 60 queries an hour from a hosting instance with 2GB of memory
- The website shall have a clean, flat theme and render pages from templates which can be modified
- The website shall create magnet links for each of the stats files downloaded from the BOINC projects and publish them in an rss feed at /torrents.xml so people can subscribe to and seed BOINC project data automatically using their torrent client.

Code requirements:
- The website must be written in python, and have adequate comments to explain its functioning with documentation on how to deploy it
- The code for the website must be released under the MIT License or a more permissive license. By claiming the bounty, you agree to transfer all ownership rights and other interests to the Science Commons Initiative, Inc.

You will need to create a demo website but do not actually need to host it beyond what is necessary for us to verify it works and award the bounty. We will secure hosting for this website independently.

**Contribute to this Bounty**
You can contribute to this bounty by donating [to SCI](https://thesciencecommons.org/donate/) directly. You will get a nice tax deduction, and we will spend those donated funds on our bounty programs. The higher the bounty, the more likely a developer will come along to claim it!

**Bounty amount: $200 USD**

Payment will be made through PayPal or DAI directly from the SCI upon completion of the work. You will also get the satisfaction of knowing you are helping a software and ecosystem which supports the progress of science. 

**Claiming bounty**

Comment below if you want to indicate you are working on the bounty (though this is not required) or if you have any questions. If the bounty amount exceeds $600 USD equivalent, you will also need to provide us with the requisite paperwork normally completed for contractors for US companies (1099-MISC).

**About SCI**
The SCI is a US 501(c)(3) non-profit organization dedicated to rebuilding the bridge of participation and trust between the public and the scientific process. We support tools and infrastructure that enable people to learn about and engage with science. Follow our work via our [free newsletter on substack](https://thesciencecommons.substack.com/).

**Comment by makeasnek** [comment]
Closing this issue as it looks like a quickmag replacement has been created already.

**Comment by Frigyes06** [comment]
Can you link the quickmag replacement for future reference?
Is it open source?

**Comment by makeasnek** [comment]
I don't believe it is open source, but it fills the niche quickmag used to https://gridcoin.ch/magnitude
