### ISSUE TITLE
Bounty: Fix confusing warning to users when directory permissions are incorrect (Linux)

### ISSUE THREAD

**Issue by makeasnek** [TheSCInitiative/bounties#7]
Context: See relevant issue in BOINC repo https://github.com/BOINC/boinc/issues/2156

**Requirements to claim bounty:**
- Submit code to BOINC repo and have it approved by maintainers, following all coding standards used by the repo and making any style and other edits requested by them. In the event that your code is not accepted by maintainers but otherwise meets bounty requirements and solves the issue the bounty is for, the bounty will still be paid out according to the BountySource terms.

**Contribute to this Bounty**
You can contribute to this bounty by donating at [BountySource](https://app.bountysource.com/issues/119785136-bounty-fix-confusing-warning-to-users-when-directory-permissions-are-incorrect-linux). You can also donate [to SCI](https://thesciencecommons.org/donate/) directly, get a nice tax deduction, and we will spend those donated funds on our bounty programs. The higher the bounty, the more likely a developer will come along to claim it!

**Bounty amount: Whatever is on BountySource**

BountySource at time of writing has $25 on the bounty. You will also get the satisfaction of knowing you are helping a software and ecosystem which supports the progress of science. 

**Claiming bounty**

Comment below if you want to indicate you are working on the bounty (though this is not required) or if you have any questions. BountySource bounty will paid under the BountySource terms (if bounty payers vote that your change fixes the issue). 

**About SCI**
The SCI is a US 501(c)(3) non-profit organization dedicated to rebuilding the bridge of participation and trust between the public and the scientific process. We support tools and infrastructure that enable people to learn about and engage with science. Follow our work via our [free newsletter on substack](https://thesciencecommons.substack.com/).

**Comment by AenBleidd** [comment]
Has beed fixed via https://github.com/BOINC/boinc/pull/5212
