### ISSUE TITLE
$100 Bounty: Poll reminders in Gridcoin wallet (C++)

### ISSUE THREAD

**Issue by makeasnek** [TheSCInitiative/bounties#9]
![btcbalance badge](https://img.shields.io/badge/dynamic/json?url=https://explorer.viawallet.com/res/btc/addresses/bc1qnwypeuth6e3lqwwlkda0pvyj6dgdqga49cyyfe&query=$.data.balance&suffix=BTC&logo=bitcoin&label=Donated)
![eth balance badge](https://img.shields.io/badge/dynamic/json?url=https://api.ethplorer.io/getAddressInfo/0x099F8dE3f82Ede035734DA56D138B2346fe6cc15?apiKey=freekey&query=$.ETH.balance&suffix=ETH&logo=ethereum&label=Donated) 
![grc balance badge](https://img.shields.io/badge/Donated-0GRC/0USD-blue?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNDMzLjAxIDUwMCI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJBIiB4MT0iMjUwIiB5MT0iNC40MSIgeDI9IjI1MCIgeTI9IjUwMSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIG9mZnNldD0iMCIgc3RvcC1jb2xvcj0iIzdmMDBmNyIvPjxzdG9wIG9mZnNldD0iLjU0IiBzdG9wLWNvbG9yPSIjNDEwMDdmIi8+PC9saW5lYXJHcmFkaWVudD48bGluZWFyR3JhZGllbnQgaWQ9IkIiIHhsaW5rOmhyZWY9IiNBIi8+PC9kZWZzPjxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0yLjQ0IDEyNi40MUwyMTYuNSAyLjgybDIxNC4wNyAxMjMuNTl2MjQ3LjE4TDIxNi41IDQ5Ny4xOCAyLjQ0IDM3My41OVYxMjYuNDF6Ii8+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTMzLjQ5KSI+PHBhdGggZD0iTTM0Mi40NiA4Mi4wOWEzNDIuMDYgMzQyLjA2IDAgMCAxLTQwLjE0IDI4LjQ1Yy0xMy4zMSA4LjE4LTI3IDE1LjgxLTQwLjI3IDIzLjIzcS02LjE1IDMuNDMtMTIuMDUgNi43OEMxODkuMzIgMTc1IDE1MC4yOCAyMDIuOTEgMTUwLjI4IDI1MGMwIDM5Ljc5IDI4IDY1LjcxIDczLjQgOTMuNDQgNS4xOCAzLjE3IDEwLjYyIDYuMzYgMTYuMjQgOS42bC02IDMuMzVjLTEzLjYxIDcuNTQtMjcuNjcgMTUuMzMtNDEuNiAyMy44OXEtMi4wOSAxLjI4LTQuMTUgMi41N2MtNC45MS0zLjItOS43Ny02LjQ2LTE0LjQ5LTkuODctNDAtMjguODYtNzEuNTItNjUuOTMtNzEuNTItMTIzIDAtNjguMDggNDQuOTMtMTA4IDk1LjUzLTEzOS40NiAxNC4xMy04Ljc5IDI4LjY5LTE2LjkxIDQyLjg1LTI0LjhsOS40Ni01LjNjMTYuMjUtOS4xOCAzMC44My0xNy44NSA0My42NS0yNi41MUwyNTAgMjguNzFsLTQzLjY2IDI1LjIxYzUuNDkgMy43MSAxMS4yMyA3LjQyIDE3LjM5IDExLjE3bDE2LjIxIDkuNTktNC4xOSAyLjMyYy0xNC4yMSA3LjkyLTI4LjkgMTYuMTItNDMuMjQgMjVsLTQuMDkgMi41OGMtNC45MS0zLjE4LTkuNzctNi40My0xNC41LTkuODEtNS42Ny00LjA2LTExLjEyLTguMzMtMTYuMzgtMTIuNzRsLTk5LjE4IDU3LjMzdjIyMS4yOGw5OC41OCA1Ni45MmEzMzIuNzUgMzMyLjc1IDAgMCAxIDQwLjUtMjguNzhjMTMuNi04LjM2IDI3LjYtMTYuMTIgNDEuMjItMjMuNjZxNS43OS0zLjIxIDExLjM0LTYuMzNjMjktMTYuMzUgNTMuMTItMzEuMjEgNzAuMzQtNDcuNDFIMjE3LjEybDMwLjk1LTUzLjcxaDE0OS41OGExMjguOTIgMTI4LjkyIDAgMCAxLTE0LjM5IDUzLjcxYy0xNy4yNCAzMy4wOS00Ny43NiA1Ny4wNi04MC42OSA3Ny40LTE0IDguNjYtMjguNDYgMTYuNjYtNDIuNTEgMjQuNDRMMjUwIDQxOC44M2MtMTYuNTQgOS4yOC0zMS4zNCAxOC4wNy00NC4zMSAyNi44N0wyNTAgNDcxLjI5bDQ0LjMzLTI1LjZhNDI2LjU4IDQyNi41OCAwIDAgMC0xNy45NS0xMS41NHEtNy44LTQuNzQtMTYuMjgtOS41OGw0LjcxLTIuNjNjMTQuMDktNy44MSAyOC42Ny0xNS44OCA0Mi45MS0yNC42N2w0LjEzLTIuNTljNC44OSAzLjE3IDkuNzMgNi4zOSAxNC40MyA5Ljc2IDUuODIgNC4xNyAxMS40IDguNTYgMTYuNzggMTMuMTJsOTguNTgtNTYuOTJWMTM5LjM2em00Ljg3IDE0OC43M2MtNy42NS0yOS42NC0zMy40LTUxLjY0LTcxLjE4LTc0LjlsLTE2LjEzLTkuNjIgNi44MS0zLjgyYzEyLjYzLTcgMjYuOTUtMTUgNDAuNjItMjMuNDVxMi4wNi0xLjI2IDQuMTEtMi41NWM0LjkgMy4yMSA5Ljc0IDYuNDkgMTQuNDUgOS45IDM1LjQ0IDI1Ljc0IDY0LjI5IDU3Ljg4IDcwLjU0IDEwNC40NHoiIGZpbGw9InVybCgjQSkiLz48cGF0aCBkPSJNMjUwLDUwMCwzMy40OSwzNzVWMTI1TDI1MCwwLDQ2Ni41MSwxMjVWMzc1Wk00NCwzNjksMjUwLDQ4Ny45Miw0NTYuMDUsMzY5VjEzMWwtMjA2LTExOUw0NCwxMzFaIiBmaWxsPSJ1cmwoI0IpIi8+PC9nPjwvc3ZnPg==) 

Context: Gridcoin polls are a useful feature which engage users, particularly in the selection of which projects are incentivized by Gridcoin. Currently, a user is only notified once upon a new poll creation, which means even though they may wish to participate, they simply forget to. Reminders should be implemented.

Relevant discussion issue: https://github.com/gridcoin-community/Gridcoin-Research/issues/2648

**Requirements to claim bounty:**
- Submit code to Gridcoin repo adding this feature and have it approved by maintainers, following all coding standards used by the repo and making any style and other edits requested by them. Note that SCI is working with Gridcoin on our bounty program and it is expected that they will integrate any well written code into their repo.
- Before writing the code itself, it would be best to make a proposal to devs about how/where the code should be integrated into existing wallet code.
- **Important: We have been alerted that some devs are having trouble withdrawing funds from BountySource. All future bounty increases will be paid out by us directly, we cannot guarantee that BountySource will release any funds currently stuck there.**

**Feature Description**

- Users should be reminded of polls which are about to close. This should be coded in such a way that is will be easy to change the frequency and conditions of these reminders in the future as Gridcoin gets feedback from users about them. 
- To start, users should be reminded three days before a poll ends, and the day a poll ends. 
- If, when a reminder would already be launched, a poll has > 80% voting against it and a current vote weight above a particular variable (to be indicated by dev team) it should be assumed to be spam and reminders should not be made
- Users should never be reminded about polls in which they have already placed votes.
- The reminder should be made through the standard notification APIs used by other wallet notifications
- The reminder should allow the user to silence all reminders for a particular poll or all reminders for all polls
- A setting should be added to "silence poll reminders" in the wallet preferences menu. The default setting should be non-silenced.

**Contribute to this Bounty**
You can contribute to SCI's bounty program by donating cash or crypto [to SCI](https://thesciencecommons.org/donate/). You will get a nice tax deduction, and we will spend those donated funds on our bounty programs. You can also support us every time you shop on Amazon and eBay, please see [our donation page](https://thesciencecommons.org/donate/) for more information.

You can donate to this bounty _specifically_ by sending crypto to the following addresses. 

BTC (Bitcoin): [bc1qnwypeuth6e3lqwwlkda0pvyj6dgdqga49cyyfe](https://blockchair.com/bitcoin/address/bc1qnwypeuth6e3lqwwlkda0pvyj6dgdqga49cyyfe) ![btcbalance badge](https://img.shields.io/badge/dynamic/json?url=https://explorer.viawallet.com/res/btc/addresses/bc1qnwypeuth6e3lqwwlkda0pvyj6dgdqga49cyyfe&query=$.data.balance&suffix=BTC&logo=bitcoin&label=Donated)
ETH (Ethereum) and DAI: [0x099F8dE3f82Ede035734DA56D138B2346fe6cc15](https://etherscan.io/address/0x099F8dE3f82Ede035734DA56D138B2346fe6cc15) ![eth balance badge](https://img.shields.io/badge/dynamic/json?url=https://api.ethplorer.io/getAddressInfo/0x099F8dE3f82Ede035734DA56D138B2346fe6cc15?apiKey=freekey&query=$.ETH.balance&suffix=ETH&logo=ethereum&label=Donated) 
GRC (Gridcoin): [S3thJGikuHD21vNs5BsykmUxR6NyTKSmp4](http://gridcoinstats.eu/address/S3thJGikuHD21vNs5BsykmUxR6NyTKSmp4) ![grc balance badge](https://img.shields.io/badge/Donated-0GRC/0USD-blue?logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgNDMzLjAxIDUwMCI+PGRlZnM+PGxpbmVhckdyYWRpZW50IGlkPSJBIiB4MT0iMjUwIiB5MT0iNC40MSIgeDI9IjI1MCIgeTI9IjUwMSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPjxzdG9wIG9mZnNldD0iMCIgc3RvcC1jb2xvcj0iIzdmMDBmNyIvPjxzdG9wIG9mZnNldD0iLjU0IiBzdG9wLWNvbG9yPSIjNDEwMDdmIi8+PC9saW5lYXJHcmFkaWVudD48bGluZWFyR3JhZGllbnQgaWQ9IkIiIHhsaW5rOmhyZWY9IiNBIi8+PC9kZWZzPjxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0yLjQ0IDEyNi40MUwyMTYuNSAyLjgybDIxNC4wNyAxMjMuNTl2MjQ3LjE4TDIxNi41IDQ5Ny4xOCAyLjQ0IDM3My41OVYxMjYuNDF6Ii8+PGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTMzLjQ5KSI+PHBhdGggZD0iTTM0Mi40NiA4Mi4wOWEzNDIuMDYgMzQyLjA2IDAgMCAxLTQwLjE0IDI4LjQ1Yy0xMy4zMSA4LjE4LTI3IDE1LjgxLTQwLjI3IDIzLjIzcS02LjE1IDMuNDMtMTIuMDUgNi43OEMxODkuMzIgMTc1IDE1MC4yOCAyMDIuOTEgMTUwLjI4IDI1MGMwIDM5Ljc5IDI4IDY1LjcxIDczLjQgOTMuNDQgNS4xOCAzLjE3IDEwLjYyIDYuMzYgMTYuMjQgOS42bC02IDMuMzVjLTEzLjYxIDcuNTQtMjcuNjcgMTUuMzMtNDEuNiAyMy44OXEtMi4wOSAxLjI4LTQuMTUgMi41N2MtNC45MS0zLjItOS43Ny02LjQ2LTE0LjQ5LTkuODctNDAtMjguODYtNzEuNTItNjUuOTMtNzEuNTItMTIzIDAtNjguMDggNDQuOTMtMTA4IDk1LjUzLTEzOS40NiAxNC4xMy04Ljc5IDI4LjY5LTE2LjkxIDQyLjg1LTI0LjhsOS40Ni01LjNjMTYuMjUtOS4xOCAzMC44My0xNy44NSA0My42NS0yNi41MUwyNTAgMjguNzFsLTQzLjY2IDI1LjIxYzUuNDkgMy43MSAxMS4yMyA3LjQyIDE3LjM5IDExLjE3bDE2LjIxIDkuNTktNC4xOSAyLjMyYy0xNC4yMSA3LjkyLTI4LjkgMTYuMTItNDMuMjQgMjVsLTQuMDkgMi41OGMtNC45MS0zLjE4LTkuNzctNi40My0xNC41LTkuODEtNS42Ny00LjA2LTExLjEyLTguMzMtMTYuMzgtMTIuNzRsLTk5LjE4IDU3LjMzdjIyMS4yOGw5OC41OCA1Ni45MmEzMzIuNzUgMzMyLjc1IDAgMCAxIDQwLjUtMjguNzhjMTMuNi04LjM2IDI3LjYtMTYuMTIgNDEuMjItMjMuNjZxNS43OS0zLjIxIDExLjM0LTYuMzNjMjktMTYuMzUgNTMuMTItMzEuMjEgNzAuMzQtNDcuNDFIMjE3LjEybDMwLjk1LTUzLjcxaDE0OS41OGExMjguOTIgMTI4LjkyIDAgMCAxLTE0LjM5IDUzLjcxYy0xNy4yNCAzMy4wOS00Ny43NiA1Ny4wNi04MC42OSA3Ny40LTE0IDguNjYtMjguNDYgMTYuNjYtNDIuNTEgMjQuNDRMMjUwIDQxOC44M2MtMTYuNTQgOS4yOC0zMS4zNCAxOC4wNy00NC4zMSAyNi44N0wyNTAgNDcxLjI5bDQ0LjMzLTI1LjZhNDI2LjU4IDQyNi41OCAwIDAgMC0xNy45NS0xMS41NHEtNy44LTQuNzQtMTYuMjgtOS41OGw0LjcxLTIuNjNjMTQuMDktNy44MSAyOC42Ny0xNS44OCA0Mi45MS0yNC42N2w0LjEzLTIuNTljNC44OSAzLjE3IDkuNzMgNi4zOSAxNC40MyA5Ljc2IDUuODIgNC4xNyAxMS40IDguNTYgMTYuNzggMTMuMTJsOTguNTgtNTYuOTJWMTM5LjM2em00Ljg3IDE0OC43M2MtNy42NS0yOS42NC0zMy40LTUxLjY0LTcxLjE4LTc0LjlsLTE2LjEzLTkuNjIgNi44MS0zLjgyYzEyLjYzLTcgMjYuOTUtMTUgNDAuNjItMjMuNDVxMi4wNi0xLjI2IDQuMTEtMi41NWM0LjkgMy4yMSA5Ljc0IDYuNDkgMTQuNDUgOS45IDM1LjQ0IDI1Ljc0IDY0LjI5IDU3Ljg4IDcwLjU0IDEwNC40NHoiIGZpbGw9InVybCgjQSkiLz48cGF0aCBkPSJNMjUwLDUwMCwzMy40OSwzNzVWMTI1TDI1MCwwLDQ2Ni41MSwxMjVWMzc1Wk00NCwzNjksMjUwLDQ4Ny45Miw0NTYuMDUsMzY5VjEzMWwtMjA2LTExOUw0NCwxMzFaIiBmaWxsPSJ1cmwoI0IpIi8+PC9nPjwvc3ZnPg==) 
Note that GRC badge does not automatically update. ETH and BTC do.

PS Did you know that crypto is one of the most effective ways to make donations (for US donors)? Cryptocurrency donations to 501(c)3 nonprofits are considered tax-deductible and do not trigger a taxable event, meaning you do not usually have to pay capital gains tax on them. We request that any individual donating over $500USD (or equivalent) provide their information along with their donation to ensure compliance with our AML and KYC policies. Any organization that wishes to make a donation to SCI is requested to reach out to us directly at contact{at}thesciencecommons.org. In the event that the awardee does not want the crypto or the bounty is closed without being paid out, it will be turned over to SCI's bounty fund to be spent on future bounties.

**Bounty amount: $100 + Whatever is on BountySource + Whatever is in above crypto addresses**

[BountySource](https://app.bountysource.com/issues/120098368-bounty-poll-reminders-in-gridcoin-wallet) at time of writing has $50 on the bounty. You will also get the satisfaction of knowing you are helping a software and ecosystem which supports the progress of science. 

**Claiming bounty**

Comment below if you want to indicate you are working on the bounty (though this is not required) or if you have any questions. BountySource bounty will paid under the BountySource terms (if bounty payers vote that your change fixes the issue). The first person to submit code to the Gridcoin repo and have it accepted will be the only one able to claim the bounty.

**About SCI**
The SCI is a US 501(c)(3) non-profit organization dedicated to rebuilding the bridge of participation and trust between the public and the scientific process. We support tools and infrastructure that enable people to learn about and engage with science. Follow our work via our [free newsletter on substack](https://thesciencecommons.substack.com/).

**Comment by jamescowens** [comment]
I will be working on this shortly and I will be refusing the bounty.

**Comment by makeasnek** [comment]
Ok yay, I will remove it from the bounty list!
